#!/bin/bash

echo "Setting up Authorize.net Production Environment Variables..."
echo ""
echo "Please run these commands manually in your terminal:"
echo ""
echo "1. Set Production Login ID:"
echo "vercel env add AUTHORIZE_NET_LOGIN_ID_PROD production"
echo "   Value: 2ww69CxS9enB"
echo ""
echo "2. Set Production Transaction Key:"
echo "vercel env add AUTHORIZE_NET_TRANSACTION_KEY_PROD production"
echo "   Value: 24rKZ83SYp44Zw3u"
echo ""
echo "3. Set Environment to Production:"
echo "vercel env add AUTHORIZE_NET_ENVIRONMENT production"
echo "   Value: production"
echo ""
echo "4. Deploy to production:"
echo "vercel --prod"
echo ""
echo "Alternative: You can also set these in the Vercel Dashboard:"
echo "- Go to your project settings"
echo "- Navigate to Environment Variables"
echo "- Add the three variables above"
